### ISSUE TITLE
Playground demo does not work?

### ISSUE THREAD

**Issue by yoav-miles-sp** [sheehan/job-dsl-playground#19]

**Comment by sheehan** [comment]
How so? It's working for me at http://job-dsl.herokuapp.com/

**Comment by daspilker** [comment]
No, the default script (https://github.com/sheehan/job-dsl-playground/blob/64de207dcd24fb38cfd22a59ba6d33d67a74dcd5/src/ratpack/templates/index.html#L48-L64) is no longer working. I forgot to adapt it to the new syntax.

**Comment by yoav-miles-sp** [comment]
Sorry for providing no information before, I have no experience with the DSL plugin.
I added a job name and put parenthesis after the name property and the default script worked again.

**Comment by sheehan** [comment]
No problem. I've updated the default now, thanks.
