### ISSUE TITLE
App seem not to be working

### ISSUE THREAD

**Issue by BG-Blaqsmite** [sheehan/job-dsl-playground#51]
App does load

**Comment by sheehan** [comment]
Are you talking about http://job-dsl.herokuapp.com/ ? It seems to be working for me.

**Comment by scoobycoder** [comment]
It seems to be down now.

"Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details."

**Comment by sheehan** [comment]
> Free app running time quota exhausted

I guess it's reached max quota for the month. 🙁

**Comment by scoobycoder** [comment]
No worries, thanks for creating this.  Have you tried getting any community funding for this?

**Comment by sheehan** [comment]
No, this is the first time this has happened AFAIK.

**Comment by triggetry** [comment]
Hi, I've tried to run the playground on my local machine, so I've built it using gradle.
The build was successful, however if I start the server via the "job-dsl-playground" script, the server starts and it is accessible via localhost:5050 but it gives me a blank page and in the logs I just see the following:

```
$ ./job-dsl-playground
[main] INFO ratpack.server.RatpackServer - Starting server...
[main] INFO ratpack.server.RatpackServer - Building registry...
[main] INFO ratpack.server.RatpackServer - Initializing 1 services...
[main] INFO ratpack.server.RatpackServer - Ratpack started for http://localhost:5050
[ratpack-compute-1-3] WARN ratpack.error.internal.DefaultProductionErrorHandler - Default production error handler used to render client error, please add a ratpack.error.ClientErrorHandler instance to your application (method: GET, uri: /assets/app.css)
[ratpack-compute-1-4] WARN ratpack.error.internal.DefaultProductionErrorHandler - Default production error handler used to render client error, please add a ratpack.error.ClientErrorHandler instance to your application (method: GET, uri: /assets/app.js)
[ratpack-compute-1-4] WARN ratpack.error.internal.DefaultProductionErrorHandler - Default production error handler used to render client error, please add a ratpack.error.ClientErrorHandler instance to your application (method: GET, uri: /assets/app.js)
```

Any suggestions how to proceed?
Or could you give instructions on how to build and run the playground on your own?

Thanks :-)

**Comment by sheehan** [comment]
@triggetry you should be able to start the app locally with:

```
./gradlew run
```
