### ISSUE TITLE
Migration Example concurrentBuild does not work in Playground with DSL-Plugin 1.76

### ISSUE THREAD

**Issue by AndreasHK** [sheehan/job-dsl-playground#59]
Following the documentation about deprecating concurrentBuild it seems that even the Playground does not work with the example given in the documentation:

```
pipelineJob('example-1') {
    properties {
        disableConcurrentBuilds()
    }
}
```

It states that the Job-DSL Version is 1.76 so the example above should work, but instead it results in 
`javaposse.jobdsl.dsl.DslScriptException: (script, line 3) No signature of method: javaposse.jobdsl.dsl.helpers.properties.PropertiesContext.disableConcurrentBuilds() is applicable for argument types: () values: []`

**Comment by sheehan** [comment]
That seems like an issue with the documentation. I don't see that option available in the [built-in docs](https://jenkinsci.github.io/job-dsl-plugin/#path/pipelineJob-properties). I think the issue should go in the [job dsl jira](https://issues.jenkins-ci.org/secure/Dashboard.jspa?selectPageId=15341).
